version: '3.5'

services:
  webapp:
    image: "app:latest"
    env_file:
      - config/docker.env
  haproxy:
    image: eeacms/haproxy
    links:
      - webapp
    ports:
      - "80:5000"
      - "1936:1936"
    environment:
      BACKENDS_PORT: "4000"
      BACKENDS: "webapp_1 webapp_2 webapp_3"
      DNS_ENABLED: "true"
